---

# run one of the cassandra_ or scylla_ containers
# for running the cquill crate's tests

# admin utilities
#  docker exec -it $CONTAINER cqlsh
#  docker exec -it $CONTAINER nodetool

# docs https://hub.docker.com/r/_/cassandra
# docs https://hub.docker.com/r/scylladb/scylla

services:

  cassandra_3:
    container_name: cassandra_3
    image: cassandra:3
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe cluster" ]
      start_period: 30s
      start_interval: 2s
      interval: 2s
      timeout: 5s
      retries: 30
    ports:
      - "9042:9042"   # CQL protocol
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=127.0.0.1

  cassandra_4:
    container_name: cassandra_4
    image: cassandra:4.1
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe cluster" ]
      start_period: 30s
      start_interval: 2s
      interval: 2s
      timeout: 5s
      retries: 30
    ports:
      - "9042:9042"   # CQL protocol
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=127.0.0.1

  cassandra_5:
    container_name: cassandra_5
    image: cassandra:5.0
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe cluster" ]
      start_period: 60s
      start_interval: 2s
      interval: 2s
      timeout: 5s
      retries: 30
    ports:
      - "9042:9042"   # CQL protocol
    environment:
      - CASSANDRA_BROADCAST_ADDRESS=127.0.0.1

  scylla_2026:
    container_name: scylla_2026
    image: scylladb/scylla:2026.1
    command: --broadcast-rpc-address 127.0.0.1
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe cluster" ]
      start_period: 30s
      start_interval: 2s
      interval: 2s
      timeout: 5s
      retries: 30
    ports:
      - "7001:7001"   # inter-node gossip
      - "9042:9042"   # CQL protocol
      - "9180:9180"   # Prometheus metrics
      - "10000:10000" # ScyllaDB API

  scylla_2025:
    container_name: scylla_2025
    image: scylladb/scylla:2025.1
    command: --broadcast-rpc-address 127.0.0.1
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe cluster" ]
      start_period: 30s
      start_interval: 2s
      interval: 2s
      timeout: 5s
      retries: 30
    ports:
      - "7001:7001"   # inter-node gossip
      - "9042:9042"   # CQL protocol
      - "9180:9180"   # Prometheus metrics
      - "10000:10000" # ScyllaDB API

  scylla_6:
    container_name: scylla_6
    image: scylladb/scylla:6.2
    command: --broadcast-rpc-address 127.0.0.1
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe cluster" ]
      start_period: 30s
      start_interval: 2s
      interval: 2s
      timeout: 5s
      retries: 30
    ports:
      - "7001:7001"   # inter-node gossip
      - "9042:9042"   # CQL protocol
      - "9180:9180"   # Prometheus metrics
      - "10000:10000" # ScyllaDB API

  scylla_5:
    container_name: scylla_5
    image: scylladb/scylla:5.4
    command: --broadcast-rpc-address 127.0.0.1
    healthcheck:
      test: [ "CMD", "cqlsh", "-e", "describe cluster" ]
      start_period: 30s
      start_interval: 2s
      interval: 2s
      timeout: 5s
      retries: 30
    ports:
      - "7001:7001"   # inter-node gossip
      - "9042:9042"   # CQL protocol
      - "9180:9180"   # Prometheus metrics
      - "10000:10000" # ScyllaDB API

  password_auth:
    container_name: password_auth
    image: scylladb/scylla:2026.1
    command: --broadcast-rpc-address 127.0.0.1 --authenticator PasswordAuthenticator
    healthcheck:
      test: [ "CMD", "cqlsh", "-u", "cassandra", "-p", "cassandra", "-e", "describe cluster" ]
      start_period: 30s
      start_interval: 2s
      interval: 2s
      timeout: 5s
      retries: 30
    ports:
      - "7001:7001"   # inter-node gossip
      - "9042:9042"   # CQL protocol
      - "9180:9180"   # Prometheus metrics
      - "10000:10000" # ScyllaDB API
