[package]
name = "cquill"
version = "0.0.9"
description = "Versioned CQL migrations for Cassandra and ScyllaDB"
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# exclude = [".*", "Dockerfile", "docker-compose.yml"]
# build = false

[lib]
name = "cquill"

[[bin]]
name = "cquill"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
configparser = { workspace = true }
md5 = { workspace = true }
regex = { workspace = true }
rustls = { workspace = true }
rustls-pki-types = { workspace = true }
scylla = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
cquill-dev-database = { path = "../dev/database" }
cquill-dev-gen-certs = { path = "../dev/gen_certs" }
rand = { workspace = true }
temp-dir = { workspace = true }
