name: Publish Linux/MacOS
run-name: "publish linux/macos ${{ inputs.tag_name }}"

on:
  workflow_call:
    inputs:
      release_id:
        required: true
        type: string
      tag_name:
        required: true
        type: string
      upload_hostname:
        required: true
        type: string

jobs:

  publish-asset:
    name: "publish ${{ matrix.filename}}"
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - filename: cquill-linux-x86_64
            runner: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
          - filename: cquill-linux-aarch64
            runner: ubuntu-24.04
            target: aarch64-unknown-linux-gnu
            apt_package_linker: gcc-aarch64-linux-gnu
          - filename: cquill-macos-x86_64
            runner: macos-latest
            target: x86_64-apple-darwin
          - filename: cquill-macos-aarch64
            runner: macos-latest
            target: aarch64-apple-darwin
    env:
      FILENAME: ${{ matrix.filename }}
      TARGET: ${{ matrix.target }}
      RELEASE_ID: ${{ inputs.release_id }}
      UPLOAD_HOSTNAME: ${{ inputs.upload_hostname }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag_name }}
      - if: ${{ matrix.apt_package_linker }}
        run: |
          sudo apt update && sudo apt install ${{ matrix.apt_package_linker }}
          mkdir -p $HOME/.cargo
          mv ./.github/workflows/linkers.toml $HOME/.cargo/config.toml
      - run: rustup install stable
      - uses: swatinem/rust-cache@v2
      - run: rustup target add $TARGET
      - name: build
        run: cargo build --release --target $TARGET
      - name: upload
        run: |
          curl --fail --silent -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: $(file target/$TARGET/release/cquill -b --mime-type)" \
            https://$UPLOAD_HOSTNAME/repos/eighty4/cquill/releases/$RELEASE_ID/assets?name=$FILENAME \
            --data-binary "@target/$TARGET/release/cquill"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
